### ISSUE TITLE
colourized output requested

### ISSUE THREAD

**Issue by dankelley** [dankelley/nb#15]
I've made the output be colourized. I think it would be a good idea to get comments here with screenshots (each with a listing of the colours used), so that I can get a better idea for good defaults.  At the moment, the default (with no colours named in ``~/.nbrc``) is as shown. I'm not nuts about the hash colour.
![screen shot 2015-02-24 at 3 05 24 pm](https://cloud.githubusercontent.com/assets/99469/6356852/a2fb1c6c-bc36-11e4-8c4d-137b53044245.png)

**Comment by richardsc** [comment]
Here is mine currently:
![screen shot 2015-02-24 at 2 00 55 pm](https://cloud.githubusercontent.com/assets/233584/6356883/8a5d38b4-bc2e-11e4-836a-985c648b2185.png)j
My `.nbrc` looks like:
```
colourize = True
colours.hash = "31m"   # red
colours.title = "1m"   # bold
colours.keyword = "4m" # underline
```

I would like to style the keywords, but I think you mentioned that isn't working yet.

Also, I see you went with the non-US spelling of "colour" :) ... (I only notice, because my machine is set to a US dictionary, so they all get red underlines in my browser)

**Comment by dankelley** [comment]
It does keywords now.

It also uses updated US styled names. To see them, either do ``nb -h`` or look at how I modified your comment above.

You can also do themes. I made up one for me (``dk1``) and hacked in one for you (``cr1``). Possibly you could alter the code and send a pull request, to make a new theme for yourself.
```
color = "dk1"
color = "cr1"
```
PS. these are just provisional themes, both in their names and their specifications. I will play with ``dk1`` a bit, and also think about the best name. To my eye, the keyword color is greenish, so I'm inclined to call this theme something like ``"forest"``.

**Comment by dankelley** [comment]
I figure this is fine now (in ``nota``)
