### ISSUE TITLE
listing notation re key number

### ISSUE THREAD

**Issue by dankelley** [dankelley/nb#8]
Right now, the ``< >`` output from ``nb`` is the internal key used in sqlite3. This is unique (that’s the whole idea of a database) so it does not get reused and therefore has gaps if notes are added and deleted.  So the output might look like
```
<11> …
<99> …
<314> …
```
etc. I just made a thing where you can do
```
nb 0
```
and it gives the most recent note (in this case #314), while ``nb -1`` gives the second most recent etc.  I like that better, but it makes me think I should do e.g.
```
1. <11> …
2. <99> …
3. <314> …
```
and then the user could maybe do
```
nb 1
```
to get the one presently numbered 1, or something like
```
nb -11
```
to get the one labelled <11>.

The actual look can change though. The use of ``<>`` is bad because you can’t type that in unix without escaping it.  So maybe the listing should be e.g.
```
1. r11 ...
2. r99 ...
3. r314 ...
```
or something, and then maybe 
```
nb -r 11
``
could give the note with reference number 11.

The idea of all of this is that there is benefit in having *fixed* keys that can get referred to at any future time.

**Comment by richardsc** [comment]
I really like the `nb 0` for most recent, `nb -1` etc.

I wonder if accessing notes via the numbering scheme is really any better than the non-sequential identifier, since the number associated with a note will change as notes are added/removed. Also, what would be displayed when searching with keywords, for example? I could imagine something like:
```
$ nb -k todo
1. <11> [todo,...
4. <23> [todo,...
16. <31> [todo,...
```
which confounds the listing with two different, non-sequential identifiers.

I like the approach that [t](http://stevelosh.com/projects/t/) uses, which is based on sha1 hashes. In the database, you can store the full hash, but all that needs to be displayed is enough of it to make sure it's unique (probably two characters at most, most of the time). E.g. my `todo` (which is based on `t`) has a "database" file that looks like:
```
organize bibdesk bibliography | id:73af23eb3e79a256e058d66e502cacf88d980b8a
organize custom scripts etc for git repo; maybe in dotfiles? | id:9a09ad5bee61400f4f701d015c1dc11c6b3d6704
contact CBP re: suzuki | id:ec5185a037e899a7aeaabd7f6e4300f1e4237c7f
```
but when I type `$ td` I see:
```
$ td
7 - organize bibdesk bibliography
9 - organize custom scripts etc for git repo; maybe in dotfiles?
e - contact CBP re: suzuki
```
This gets around the issue of ever increasing identifiers, and tosses the whole "ordering" issue out with it.

**Comment by dankelley** [comment]
This is a good discussion, thanks. I'm being a bit brain-dead, and can't remember where to get ``t``. It's not easy to google for. I can remember vaguely using it in the past but now it's escaping me.

**Comment by dankelley** [comment]
In my version (not pushed) it now displays as follows. I like putting kw at end but am not sure if I like ``[`` or some other notation etc. For the terminal I can also spit out colours, and I may do that as an option.

Note: it lists by time.  I like that (although I can make it list by anything else) because I tend to use this mainly as a to-do list. 

```
$ nb
4a - timing to build oce [ oce, computer, benchmark ]
5c - data(turbulence) in OAR [ oar ]
89 - nb -h does not show no-hyphen style [ nb ]
d8 - oar will not build [ oar ]
af - nb key-reference idea [ nb ]
5b - python boldface output [ nb, python ]
```

**Comment by richardsc** [comment]
Sorry, I linked the letter "t", but of course it was so small you can't tell it's a link. Here it is:

http://stevelosh.com/projects/t/

I like that output! I think listing by time makes sense -- that is consistent with other (way fancier) note apps, like Apple Notes.

The output you have above is obviously quite similar to `t` -- what I like about `nb` is that I can do the one liners as simple reminders, but I can also bury more info inside the note, kind of like a journal for particular tasks.

I also like kw at end instead of beginning. The title of the note is more important than a (potentially long) list of keywords.

**Comment by dankelley** [comment]
FYI, in some testing I found hashes that matched to 3 chars. That seems wildly unlikely (1 in 2 million) so I don't expect to see it again!

**Comment by dankelley** [comment]
I updated both ``master`` and ``develop`` to show e.g. 2 hash chars if at least any entry would be duplicated by specifying just 1 char.

I also could do a trick where it further trimmed, so e.g. the list
```
a1 - foo
0b - bar
a2 - foobar
75 - barfoo
```
could become
```
a1 - foo
0  - bar
a2 - foobar
7  - barfoo
```
or
```
a1 - foo
 0 - bar
a2 - foobar
 7 - barfoo
```
but I'm not sure I find that pleasing either of those blank-containing ones easy on the eye.

Thoughts on this format, CR?

**Comment by richardsc** [comment]
I like the aesthetics of trimming all displayed hashes to the same number of characters.

I'm not sure what I think about the `#`. Visually, because it takes up the first space of the hash, I find it interrupts my own "sorting" of the displayed hashes -- e.g. I have to look *through* at least two characters to get the hash of the one I want. In other words, it kind of undoes the uniqueness of each hash, by making them all look like they have a character in common. What about using a ` : ` as a separator?

You mentioned the idea of being able to reference notes, that could be a good use of the ` # ` character, which is sort of consistent with the twitter and github uses.

**Comment by dankelley** [comment]
I agree with your analysis.  I knew I didn't like the ``#`` but didn't know *why* I didn't like it. Now, the ``develop`` branch gives as follows
```
nb 
```
yields
```
a1: timing to build oce [ oce, computer, benchmark ]
0b: data(turbulence) in OAR [ oar ]
a2: oar will not build [ oar ]
d0: python boldface output [ nb, python ]

HINT: to show e.g. note with hash 'ab...', type "nb ab"
``
and
```
nb d
```
gives as follows (note that I give 7 chars here, like git tends to do; this will be enough for a cross-reference in most conceivable circumstances I guess).
```
d0d253e: python boldface output [ nb, python ]
  created 2015-02-21 10:06:28 
(ETC)
```

PS. I don't know what a cross-ref might actually do. Maybe it will just do nothing -- up to the user to do something if they like. But somehow I could see something developing e.g. maybe if the title had "re #hash" then it would get shown threaded or something.

**Comment by richardsc** [comment]
I like this version. I would also really like some decoration (boldface, colors, etc). It would be pretty neat to be able to specify that from the `~/.nbrc`.

About the trimming -- I wonder if it makes sense to always trim to the minimum number of unique chars, no matter what the output of a particular query is (e.g. with an `nb -k ...` search). An example: say you have the following db:
```
a1: foo [foo]
a2: bar [bar]
b1: foobar [foo, bar]
```

Doing `$ nb -k bar` will give:
```
a: bar [bar]
b: foobar [foo, bar]
```
but doing `$ nb -k foo` gives:
```
a: foo [foo]
b: foobar [foo, bar]
```
Because in each case the hash that starts with `a` is unique, but only in the limited context. This implies that one could do `$ nb a` to get a unique note, but would in fact produce a list of two of them. The alternative would just be:
```
$ nb -k bar
a2: bar [bar]
b1: foobar [foo, bar]
$ nb -k foo
a1: foo [foo]
b1: foobar [foo, bar]
```

**Comment by dankelley** [comment]
Excellent point. I will make ``nb`` show the number of hash chars that is needed for the whole deck of notes, even when just a subset is being displayed.  I was losing track of the actual purpose of showing the hashes!

**Comment by dankelley** [comment]
I feel that this is fixed.
